spring:
  datasource:
#    url: jdbc:mysql://localhost/hotel_model?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: BC6310
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:sqlserver://nazar-server.database.windows.net:1433;database=lab1db;user=nazar@nazar-server;password=123Shpak;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

    url: jdbc:sqlserver://nazar-server.database.windows.net:1433;database=lab1db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: nazar
    password: 123Shpak
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    open-in-view: false
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.SQLServer2016Dialect

  mvc:  # the fix for swagger
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9090

